name: assignment-test
on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container:
          image: cuaesd/aesd-autotest:assignment6-yocto
          options: --user 1001
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
            name: Checkout submodules
            run : git submodule update --init --recursive
          - uses: textbook/git-checkout-submodule-action@2.1.1
          - name: Run full test
            env:
              SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
            run: ./full-test.sh

